
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Getting Data Project

In this project, we are going to try to answer this question with data:

> "How does the price of a bestselling book relate to how much the author is charging for that book?"

To answer our question, we need some information on books on the Leanpub website. Be sure you have followed the steps described in the previous chapter and have your Googlesheets with Leanpub data prepared and ready.

### Starting up this project

1. Go to the DataTrail workspace
3. Return to your own `DataTrail_Projects` project. Click on it to start this assignment. 
4. For this project, go to the `02_Getting_Data` folder.
5. Click on the file `leanpub_project.Rmd` to open this file.

### Your objectives!

To complete this project you'll need to do a few things within this file.  

1. Go through this notebook, reading along.

2. Fill in empty or incomplete code chunks when prompted to do so.

3. Run each code chunk as you come across it by clicking the tiny green triangles at the right of each chunk. You should see the code chunks print out various output when you do this.

4. At the very top of this file, put your own name in the `author:` place. Currently it says `"DataTrail Team"`. Be sure to put your name in quotes.

5. In the `Conclusions` section, write up responses to each of these questions posed here.

6. When you are satisfied with what you've written and added to this document you'll need to save it. In the menu, go to `File` > `Save`. Now the `nb.html` output resulting file will have your new output saved to it.

7. Open up the resulting `leanpub_project.nb.html` file and click `View in Web Browser`. Does it look good to you? Did all the changes appear here as you expected.

8. Upload this file to your Google Drive folder!

7. Pat yourself on the back for finishing this project!
