## Where to get open source data

Often times for a particular project, you will have data given to you to work with. But sometimes you may want to go out and find data to work with for a particular question. In this section, we will give you some places you can go to get open source data that is freely available for you to use! Just make sure that you attribute where you got the data from originally

## dslabs

[dslabs](https://cran.r-project.org/web/packages/dslabs/index.html)

There's 26 datasets already set up in R for you.
To use the datasets in this package you need to do the following kind of steps:
```r
# Install the package
install.packages("dslabs")
library(dslabs)
```

For the dataset `admissions` for example, you first need to prep it with `data()` function and then you can call it as an object.
```r
data(admissions)
admissions
```

## FiveThiryEight Data

There's a variety of datasets available as CSVs.

[Go to the GitHub](https://github.com/fivethirtyeight/data)
When you find the dataset you are interested in, click on that folder and then click on the data file you are interested in.
Then click `Raw`.
Copy and paste the URL that that brings you to.
For example, for the `airline-safety` dataset, the URL would look like this:
```
https://raw.githubusercontent.com/fivethirtyeight/data/master/airline-safety/airline-safety.csv
```
Then you can use that URL in a read_csv function like this:
```r
airline_safety <- readr::read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/airline-safety/airline-safety.csv")
```

## Kaggle

[Kaggle](https://www.kaggle.com/datasets) has a variety of datasets that are generally available as CSV.
You'll have to make a login before you download, but you can use a Google login.

To download a dataset, you can browse them and then when you find one you like, you can download the CSV. It will download it in a zip file. Upload this to your RStudio server using the Upload button.

Then you will see a CSV included in that data file and you can use `readr::read_csv()`to read in the file.

For example, for the [Data Science Job Salaries dataset](https://www.kaggle.com/datasets/ruchi798/data-science-job-salaries), you can click `Download` and then upload the resulting zip file. Then you can read in the file like:
```r
readr::read_csv("ds_salaries.csv")
```

## More places to get data

There are endless numbers of places on the internet to get data. Above are some great ones to get started with. But as you get more comfortable with data analysis, you may want to look at some of these other sources. Some of these source will require a bit more work to get these data, but are just as available for you to use.

- [Open Case Studies](https://www.opencasestudies.org/)
- [Top 100 Open Source Datasets for Data Science](https://medium.com/analytics-vidhya/top-100-open-source-datasets-for-data-science-cd5a8d67cc3d)
- [10 Open-Source Dataset Finders For Your Next ML Project](https://towardsdatascience.com/10-open-source-dataset-finders-for-your-next-ml-project-c8d01679160d)
- [UCI Machine Learning repository](https://archive.ics.uci.edu/ml/datasets.php)
- [World Health Organization Datasets](https://www.who.int/data/collections)
- [Mapping police violence](https://mappingpoliceviolence.us/)
- [Center for Disease Control Data](https://www.cdc.gov/datastatistics/index.html)
- [Forensic science data portal](https://forensicstats.org/data/)
- [Google Public Data Explorer](https://www.google.com/publicdata/directory)
