
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Stats Project

In this project, we are going to try to answer this question with data:

> "What relationships are there between different countries' social stats?""

Note that this is a very open ended question. Given that we have discussed different kinds of of statistical models and questions, what kind of question is this?

To explore this question, we'll return to the dataset we used from the United Nations in our project from the Cleaning the Data chapter.

### Starting up this project

1. Go to the DataTrail workspace
2. Return to your own `DataTrail_Projects` project in RStudio.
3. For this project, go to the `05_Get_the_Stats` folder.
4. Click on the file `countries_stats_project.Rmd` to open this file.

### Your objectives!

To complete this project you'll need to do a few things within this file.  

1. Go through this notebook, reading along.

2. Fill in empty or incomplete code chunks when prompted to do so.

3. Run each code chunk as you come across it by clicking the tiny green triangles at the right of each chunk. You should see the code chunks print out various output when you do this.

4. At the very top of this file, put your own name in the `author:` place. Currently it says `"DataTrail Team"`. Be sure to put your name in quotes.

5. In the `Conclusions` section, write up responses to each of these questions posed here.

6. When you are satisfied with what you've written and added to this document you'll need to save it. In the menu, go to `File` > `Save`. Now the `nb.html` output resulting file will have your new output saved to it.

7. Open up the resulting `countries_stats.nb.html` file and click `View in Web Browser`. Does it look good to you? Did all the changes appear here as you expected.

8. Upload your `Rmd` and your `nb.html` to your assignment folder (this is something that will be dependent on what your instructors have told you -- or if you are taking this on your own, just collect these projects in one spot, preferably a Google Drive)!

9. Pat yourself on the back for finishing this project!
